version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - brndnmtthws
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.12.0
    - 4.15.2
    - 4.18.0
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: "@types/libsodium-wrappers"
    versions:
    - 0.7.8
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
