---
stages:
  - dependencies
  - build
  - test
  - checks

variables:
  DOCKER_DRIVER: overlay2

image: node:lts

cache:
  paths:
    - node_modules/

install dependencies:
  stage: dependencies
  script:
    - yarn install
  tags:
    - docker

build dist:
  stage: build
  script:
    - yarn run build
  tags:
    - docker

run tests:
  stage: test
  # allow test failures for now since there aren't any tests
  allow_failure: true
  script:
    - yarn run test

check style:
  stage: checks
  script:
    - yarn run prettier -c src/**

check tslint:
  stage: checks
  script:
    - yarn tslint -c tslint.json src/**/*.ts
