steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'yarn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'dist/*', 'gs://staging.umpyre.io/']
