steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'yarn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'yarn'
    args: ['run', 'test']
    env:
      - 'CI=true'
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'sh'
    args:
      [
        '-c',
        'apt-get update -yqq ; apt-get install -yqq xvfb xorg libgtk-3-0 libxss1 libgconf-2-4 libnss3 libasound2 libcups2 libatk1.0-0 libatk-bridge2.0-0 && yarn run build',
      ]
    env:
      - 'DEBIAN_FRONTEND=noninteractive'
      - 'PUBLIC_URL=https://staging.umpyre.io'
      - 'API_URL=https://api.staging.umpyre.io'
  - name: 'gcr.io/cloud-builders/gsutil'
    # First copy everything excluding index.html. This provides us with some
    # atomicity, and reduces the likelihood of people winding up in a weird
    # state.
    args: ['-m', 'rsync', '-x', 'index\.html$', '-r', 'build', 'gs://staging.umpyre.io/']
  - name: 'gcr.io/cloud-builders/gsutil'
    # Rerun the sync, this time include index.html.
    args: ['-m', 'rsync', '-r', 'build', 'gs://staging.umpyre.io/']
