steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'yarn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'yarn'
    args: ['run', 'test']
    env:
      - 'CI=true'
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'yarn'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', 'build', 'gs://staging.umpyre.io/']
