steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'yarn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'yarn'
    args: ['run', 'test']
    env:
      - 'CI=true'
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'sh'
    # libx11 is required for chrome headless installation
    args:
      [
        '-c',
        'apt-get update -qq ; DEBIAN_FRONTEND=noninteractive apt-get install -yqf xorg && yarn build',
      ]
    env:
      - 'PUBLIC_URL=https://staging.umpyre.io'
      - 'API_URL=https://api.staging.umpyre.io'
  - name: 'gcr.io/cloud-builders/gsutil'
    # First copy everything excluding index.html. This provides us with some
    # atomicity, and reduces the likelihood of people winding up in a weird
    # state.
    args: ['-m', 'rsync', '-x', 'index\.html$', '-r', 'build', 'gs://staging.umpyre.io/']
  - name: 'gcr.io/cloud-builders/gsutil'
    # Rerun the sync, this time include index.html.
    args: ['-m', 'rsync', '-r', 'build', 'gs://staging.umpyre.io/']
