steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'yarn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'yarn'
    args: ['run', 'test']
    env:
      - 'CI=true'
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'sh'
    args:
      [
        '-c',
        'apt-get update -yqq ; apt-get install -yqq xvfb xorg libgtk-3-0 libxss1 libgconf-2-4 libnss3 libasound2 libcups2 libatk1.0-0 libatk-bridge2.0-0 && yarn run build',
      ]
    env:
      - 'DEBIAN_FRONTEND=noninteractive'
      - 'PUBLIC_URL=https://staging.umpyre.io'
      - 'API_URL=https://api.staging.umpyre.io'
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      [
        '-m',
        'cp',
        '-r',
        '-z',
        'html,css,js,map,mjs,txt,woff,woff2,svg,json',
        'build/*',
        'gs://staging.umpyre.io/',
      ]
